apiVersion: v1
kind: ConfigMap
metadata:
  name: event-configmap
  namespace: api-service
data:
  KAFKA_BROKER_LIST: "KAFKA_BROKER_LIST"
  AXON_CLIENT_ID: "AXON_CLIENT_ID"
  MONGODB_URI: "MONGODB_URI"
  AXON_TRANSACTION_ID_PREFIX: "AXON_TRANSACTION_ID_PREFIX"
  AXON_DATASTORE_NAME: "AXON_DATASTORE_NAME"
  AXON_SERVER_HOST: "AXON_SERVER_HOST"
  AXON_SERVER_PORT: "AXON_SERVER_PORT"