# FROM https://github.com/eventuate-tram/eventuate-tram-sagas-examples-customers-and-orders & eventuate-tram example
version: '3.5'
services:
  cdc-service:
    image: eventuateio/eventuate-cdc-service:0.15.0.RELEASE
    ports:
      - "8099:8080"
    environment:
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: {KAFKA_SERVER_HOST}:{KAFKA_SERVER_PORT}
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: {KAFKA_ZOOKEEPER_HOST}:{KAFKA_ZOOKEEPER_PORT}

      EVENTUATE_CDC_READER_READER1_TYPE: mysql-binlog
      EVENTUATE_CDC_READER_READER1_DATASOURCEURL: jdbc:mysql://{MYSQL_SERVER_HOST}:${MYSQL_SERVER_PORT}/saga_service
      EVENTUATE_CDC_READER_READER1_MONITORINGSCHEMA: saga_service
      EVENTUATE_CDC_READER_READER1_DATASOURCEUSERNAME: {DATABASE_USER}
      EVENTUATE_CDC_READER_READER1_DATASOURCEPASSWORD: {DATABASE_PASSWORD}
      EVENTUATE_CDC_READER_READER1_DATASOURCEDRIVERCLASSNAME: com.mysql.cj.jdbc.Driver
      EVENTUATE_CDC_READER_READER1_LEADERSHIPLOCKPATH: /eventuate/cdc/leader/saga_service
      EVENTUATE_CDC_READER_READER1_CDCDBUSERNAME: {DATABASE_USER}
      EVENTUATE_CDC_READER_READER1_CDCDBPASSWORD: {DATABASE_PASSWORD}
      EVENTUATE_CDC_READER_READER1_READOLDDEBEZIUMDBOFFSETSTORAGETOPIC: "false"
      EVENTUATE_CDC_READER_READER1_MYSQLBINLOGCLIENTUNIQUEID: 1
      EVENTUATE_CDC_READER_READER1_OFFSETSTOREKEY: MySqlBinlogCustomerService
      EVENTUATE_CDC_READER_READER1_OFFSETSTORAGETOPICNAME: db.history.common
      EVENTUATE_CDC_READER_READER1_OUTBOXID: 1

      #      EVENTUATE_CDC_READER_READER2_TYPE: mysql-binlog
      #      EVENTUATE_CDC_READER_READER2_DATASOURCEURL: jdbc:mysql://order-service-mysql:3306/order_service
      #      EVENTUATE_CDC_READER_READER2_MONITORINGSCHEMA: order_service
      #      EVENTUATE_CDC_READER_READER2_DATASOURCEUSERNAME: root
      #      EVENTUATE_CDC_READER_READER2_DATASOURCEPASSWORD: rootpassword
      #      EVENTUATE_CDC_READER_READER2_DATASOURCEDRIVERCLASSNAME: com.mysql.cj.jdbc.Driver
      #      EVENTUATE_CDC_READER_READER2_LEADERSHIPLOCKPATH: /eventuate/cdc/leader/order_service
      #      EVENTUATE_CDC_READER_READER2_CDCDBUSERNAME: root
      #      EVENTUATE_CDC_READER_READER2_CDCDBPASSWORD: rootpassword
      #      EVENTUATE_CDC_READER_READER2_READOLDDEBEZIUMDBOFFSETSTORAGETOPIC: "false"
      #      EVENTUATE_CDC_READER_READER2_MYSQLBINLOGCLIENTUNIQUEID: 2
      #      EVENTUATE_CDC_READER_READER2_OFFSETSTOREKEY: MySqlBinlogOrderService
      #      EVENTUATE_CDC_READER_READER2_OFFSETSTORAGETOPICNAME: db.history.common
      #      EVENTUATE_CDC_READER_READER2_OUTBOXID: 2

      EVENTUATE_CDC_PIPELINE_PIPELINE1_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINE1_READER: reader1
      EVENTUATE_CDC_PIPELINE_PIPELINE1_EVENTUATEDATABASESCHEMA: saga_service

#      EVENTUATE_CDC_PIPELINE_PIPELINE2_TYPE: eventuate-tram
#      EVENTUATE_CDC_PIPELINE_PIPELINE2_READER: reader2
#      EVENTUATE_CDC_PIPELINE_PIPELINE2_EVENTUATEDATABASESCHEMA: order_service