apiVersion: v1
kind: Service
metadata:
  name: auth-client-svc
  namespace: api-service
spec:
  ports:
    - name: auth-client-svc
      port: 80
      targetPort: 80
  selector:
    app: auth-client
  type: ClusterIP