spring:
  config:
    activate:
      on-profile: axon-settings

  data:
    mongodb:
      uri: ${MONGODB_URI}

# https://docs.axoniq.io/reference-guide/extensions/kafka
axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  # Use MongoDB with Axon
  axonserver:
    servers: ${AXON_SERVER_URLS}
    token: ${AXON_ACCESS_TOKEN}
  #      enable-auto-commit: true
#      auto-commit-interval: 3000

  mongo:
    database-name: ${AXON_DATASTORE_NAME}
    token-store:
      enabled: true
    saga-store:
      enabled: true
    event-store:
      enabled: true
