spring:
  profiles:
    group:
      "jwt": "jwt-configuration, database-setup"
      "oauth": "jwt-configuration, database-setup"
---
spring:
  config:
    activate:
      on-profile: "jwt-configuration"

jwt:
  token:
    accessTokenExpiredTime: ACCESS_EXPIRED_TIME
    refreshTokenExpiredTime: REFRESH_EXPIRED_TIME
    keystore:
      classpath: YOUR_KEY_NAME.jks
      password: YOUR_PASSWORD
    key:
      alias: YOUR_ALIAS
      privateKeyPassPhrase: YOUR_PASS_PHRASE
---
spring:
  config:
    activate:
      on-profile: "database-setup"
  datasource:
    driver-class-name: ${YOUR_DATABASE_DRIVER}
    url: ${YOUR_DATABASE_URL}
    username: ${YOUR_DATABASE_USER_NAME}
    password: ${YOUR_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
---