spring:
  profiles:
    group:
      "local": "default-base, hikari-default-config, h2-local-database"
      "slack-service": "slack, slack-bolt"

    active: local, slack-service
---
server:
  port: 9898
  servlet:
    session:
      timeout: 5000
spring:
  config:
    activate:
      on-profile: "default-base"

  jpa:
    hibernate:
      naming: # camelCase -> under_score_case, '.' -> '_', UPPER_CASE is not allowed. changed to lower_case
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false #About Lazy fetch

management:
  endpoint:
    logfile:
      external-file: ~/logback.log
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,loggers,metrics,mappings,threaddump,conditions,info,heapdump
      base-path: /api/actuator
      path-mapping:
        loggers: logs
        httptrace: trace
info:
  spring:
    framework:
      version: ${spring-framework.version}
  java:
    version: ${java.version}

core:
  requester:
    config:
      baseUrl: "https://slack.com/api/" # Slack Requester BaseURL
---
spring:
  config:
    activate:
      on-profile: "hikari-default-config"
  datasource:
    hikari:
      transaction-isolation: TRANSACTION_REPEATABLE_READ
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: 5000
      validation-timeout: 3000
      connection-test-query: SELECT 1
      idle-timeout: 60000
      max-lifetime: 1800000
      pool-name: default_hikari_pool
---
spring:
  config:
    activate:
      on-profile: "h2-local-database"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MariaDB;DATABASE_TO_LOWER=TRUE
    jdbcUrl: jdbc:h2:mem:test;MODE=MariaDB;DATABASE_TO_LOWER=TRUE
    username: admin
    password: admin
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    database: h2
  sql:
    init:
      mode: embedded
---
spring:
  config:
    activate:
      on-profile: "slack"

slack:
  api:
    token: API_TOKEN_VALUE
    channel: BOT_CHANNEL_NAME
    signingSecret: SIGNING_SECRET_VALUE
  app:
    token: APP_API_TOKEN_VALUE