spring:
  profiles:
    group:
      "local": "core-redis-embedded, default-base, hikari-default-config, h2-local-database, settings"
      "dev": "core-redis-cluster, default-base, hikari-default-config, dev-oracle-database, settings"
      "slack-service": "slack, slack-bolt"

    active: local, slack-service
---
server:
  port: 9898
  servlet:
    session:
      timeout: 5000
spring:
  config:
    activate:
      on-profile: "default-base"

  jpa:
    hibernate:
      naming: # camelCase -> under_score_case, '.' -> '_', UPPER_CASE is not allowed. changed to lower_case
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false #About Lazy fetch

management:
  endpoint:
    logfile:
      external-file: ~/logback.log
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,loggers,metrics,mappings,threaddump,conditions,info,heapdump
      base-path: /api/actuator
      path-mapping:
        loggers: logs
        httptrace: trace
info:
  spring:
    framework:
      version: ${spring-framework.version}
  java:
    version: ${java.version}

core:
  requester:
    config:
      baseUrl: "https://slack.com/api/" # Slack Requester BaseURL
---
spring:
  config:
    activate:
      on-profile: "hikari-default-config"
  datasource:
    hikari:
      transaction-isolation: TRANSACTION_REPEATABLE_READ
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: 5000
      validation-timeout: 3000
      connection-test-query: SELECT 1
      idle-timeout: 60000
      max-lifetime: 1800000
      pool-name: default_hikari_pool
---
spring:
  config:
    activate:
      on-profile: "h2-local-database"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MariaDB;DATABASE_TO_LOWER=TRUE
    jdbcUrl: jdbc:h2:mem:test;MODE=MariaDB;DATABASE_TO_LOWER=TRUE
    username: admin
    password: admin
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    database: h2
  sql:
    init:
      mode: embedded
---
# Develop SQL - Oracle Database 19c
spring:
  config:
    activate:
      on-profile: "dev-oracle-database"
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@${DEV_TNS_NAME}?TNS_ADMIN=${DEV_ORACLE_WALLET_DIRECTORY}
    username: ${DEV_ORACLE_USER_NAME}
    password: ${DEV_ORACLE_DB_PASSWORD}
    hikari:
      connection-test-query: SELECT 1 FROM DUAL # Oracle Database Connection Query.
      transaction-isolation: TRANSACTION_READ_COMMITTED # READ_COMMITTED and SERIALIZABLE are the only valid transaction levels ( Oracle )
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true #Show Beautify sql2
    database: ORACLE
    database-platform: org.hibernate.dialect.OracleDialect
  h2: # Disable Local h2 database.
    console:
      enabled: false
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
---
spring:
  config:
    activate:
      on-profile: "slack"

slack:
  api:
    token: ${API_TOKEN_VALUE}
    channel: ${BOT_CHANNEL_NAME}
    signingSecret: ${SIGNING_SECRET_VALUE}
  app:
    token: ${APP_TOKEN}
---
spring:
  config:
    activate:
      on-profile: "settings"

assistant:
  app:
    event:
      tracking:
        type: jpa

event:
  logs:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: core-redis-cluster

  data:
    redis:
      cluster:
        nodes: ${YOUR_REDIS_CLUSTER_NODES}
      password: ${REDIS_CLUSTER_PASSWORD}
---
spring:
  config:
    activate:
      on-profile: core-redis-embedded

core:
  embedded:
    redis:
      port: 6379