apiVersion: v1
kind: Secret
metadata:
  name: api-core-secret
  namespace: api-service
type: Opaque
data:
  YOUR_REDIS_CLUSTER_NODES: YOUR_REDIS_CLUSTER_NODES
  REQUESTER_BASE_URLS: REQUESTER_BASE_URLS
  REQUESTER_AUTHORIZATION_TOKEN: REQUESTER_AUTHORIZATION_TOKEN
  REDIS_CLUSTER_PASSWORD: REDIS_CLUSTER_PASSWORD
  EMBEDDED_REDIS_PORT: EMBEDDED_REDIS_PORT