name: Gateway-App-Test
on:
  push:
    branches:
      - "feat/**"
    paths:
      - "common/**" #Common Module
      - "gateway/**" #Gateway Application
      - "*.gradle"

permissions:
  contents: read

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            common:
              - 'common/**'
            gateway:
              - 'gateway/**'

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test step
        run: ./gradlew clean :common:test :gateway:test